server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/houseKeeping?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: info

mybatis:
  mapper-locations: classpath:mapper/*.xml